name: Travel Duration Scheduler

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at minute 0 (UTC time)
  workflow_dispatch:      # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest
    concurrency:
      group: travel-duration-scheduler
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use a stable Python version

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --force-reinstall -r requirements.txt

      - name: List installed packages
        run: |
          pip list

      - name: Debug serpapi package
        run: |
          python -c "import serpapi; print(dir(serpapi))"

      - name: Run script
        env:
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
        run: |
          python travel_duration_scheduler.py

      - name: Commit CSV file
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add travel_durations.csv
          git commit -m 'Update travel durations [skip ci]' || echo "No changes to commit"
          git pull --rebase
          git push origin ${{ github.ref }}
